// Generated by dsh-plugin-prepare. Do not edit.
const manifest = {"name":"github-integration","skills":["dsh-plugin-assets/skills/0"]}
export const name = "github-integration"
export const inject = ["loader","skills"]
export async function apply(ctx) {
  const runtime = ctx.loader.builtins["dsh-repository-plugin"]
  if (runtime === undefined) throw new Error("missing Cordis builtin dsh-repository-plugin")
  await ctx.plugin(runtime, { baseUrl: import.meta.url, manifest })
}
